import os
import re
import shutil

import fitz

from src.settings import (
    PRODUCT_IMAGE_DIRNAME,
    PRODUCT_IMAGE_MARKER_FILENAME,
    PRODUCT_IMAGE_SCALE,
    TOC_CHAPTER_MATCH_THRESHOLD,
    TOC_CHAPTER_PATTERNS,
    TOC_KEYWORDS,
)
from src.infrastructure.file_ops import is_program_owned_image_dir
from src.utils.timestamps import get_beijing_timestamp_for_filename


def _normalize_text(text):
    return (text or "").strip().lower()


def _count_chapter_matches(text):
    match_count = 0
    for pattern in TOC_CHAPTER_PATTERNS:
        match_count += len(re.findall(pattern, text, flags=re.IGNORECASE))
    return match_count


def find_toc_page_index(pdf_path, max_scan_pages=20):
    try:
        with fitz.open(pdf_path) as doc:
            scan_count = min(len(doc), max_scan_pages)
            for page_index in range(scan_count):
                # TOC detection intentionally relies on the text layer only.
                # If the PDF is image-only, we skip TOC generation instead of using OCR.
                text = _normalize_text(doc[page_index].get_text("text"))
                if not text:
                    continue
                if any(keyword in text for keyword in TOC_KEYWORDS):
                    return page_index
                # Some books never print an explicit "contents" label, but the page still
                # looks like a TOC because it lists many chapter headings in sequence.
                if _count_chapter_matches(text) >= TOC_CHAPTER_MATCH_THRESHOLD:
                    return page_index
    except Exception:
        return None
    return None


def select_content_page_indexes(page_count, exclude_indexes=None, preview_count=2):
    exclude_indexes = set(exclude_indexes or [])
    if page_count <= 1 or preview_count <= 0:
        return []

    candidate_indexes = [idx for idx in range(1, page_count) if idx not in exclude_indexes]
    if not candidate_indexes:
        return []

    # Content previews should represent the body of the book instead of the front matter.
    # We anchor them at 30% and 65% of the total pages, then move forward to the next
    # available page if the target page is reserved for cover or TOC.
    target_ratios = [0.30, 0.65]
    target_indexes = [max(5, round((page_count - 1) * ratio)) for ratio in target_ratios[:preview_count]]

    selected = []
    for target_index in target_indexes:
        chosen_index = None
        for page_index in candidate_indexes:
            if page_index >= target_index and page_index not in selected:
                chosen_index = page_index
                break
        if chosen_index is None:
            for page_index in reversed(candidate_indexes):
                if page_index not in selected:
                    chosen_index = page_index
                    break
        if chosen_index is not None:
            selected.append(chosen_index)
    return sorted(set(selected))


def _render_page(page, output_path):
    matrix = fitz.Matrix(PRODUCT_IMAGE_SCALE, PRODUCT_IMAGE_SCALE)
    pixmap = page.get_pixmap(matrix=matrix, alpha=False)
    pixmap.save(output_path)


def generate_pdf_preview_images(pdf_path, output_dir):
    if not os.path.exists(pdf_path):
        return []

    # Product screenshots are temporary merchandising assets, not delivery files.
    # They live in a dedicated folder so the archive/export logic can exclude them cleanly.
    image_dir = os.path.join(output_dir, PRODUCT_IMAGE_DIRNAME)
    # We only replace folders previously generated by the tool itself.
    # This avoids deleting a manually curated folder that happens to share the same name.
    if is_program_owned_image_dir(image_dir):
        shutil.rmtree(image_dir)
    os.makedirs(image_dir, exist_ok=True)
    with open(os.path.join(image_dir, PRODUCT_IMAGE_MARKER_FILENAME), "w", encoding="utf-8") as marker_file:
        marker_file.write("Generated by BookFlow.\n")

    generated_paths = []
    timestamp = get_beijing_timestamp_for_filename()

    try:
        with fitz.open(pdf_path) as doc:
            if len(doc) == 0:
                return []

            # The first page is treated as the default cover preview.
            # Filenames follow reading order so sellers can upload them directly
            # without manually re-sorting the cover, TOC and body previews.
            cover_path = os.path.join(image_dir, f"01_封面_p001_{timestamp}.png")
            _render_page(doc[0], cover_path)
            generated_paths.append(cover_path)

            toc_page_index = find_toc_page_index(pdf_path)
            # Keep TOC out of content previews so the reading preview stays varied.
            content_indexes = select_content_page_indexes(
                len(doc),
                exclude_indexes={0, toc_page_index} if toc_page_index is not None else {0},
                preview_count=2,
            )

            if toc_page_index is not None:
                toc_path = os.path.join(image_dir, f"02_目录_p{toc_page_index + 1:03d}_{timestamp}.png")
                _render_page(doc[toc_page_index], toc_path)
                generated_paths.append(toc_path)

            for output_index, page_index in enumerate(content_indexes, start=3):
                content_path = os.path.join(image_dir, f"{output_index:02d}_内页_p{page_index + 1:03d}_{timestamp}.png")
                _render_page(doc[page_index], content_path)
                generated_paths.append(content_path)
    except Exception:
        return []

    return generated_paths
