from pathlib import Path

from src.infrastructure.file_ops import (
    clear_generated_artifacts,
    collect_delivery_files,
    copy_directory_filtered,
    is_generated_helper_file,
    is_program_owned_image_dir,
)
from src.settings import PRODUCT_IMAGE_MARKER_FILENAME


def test_collect_delivery_files_only_returns_supported_delivery_formats(tmp_path: Path):
    (tmp_path / "a.pdf").write_text("", encoding="utf-8")
    (tmp_path / "b.txt").write_text("", encoding="utf-8")
    (tmp_path / "c.docx").write_bytes(b"")
    (tmp_path / "d.epub").write_text("", encoding="utf-8")
    (tmp_path / "商品介绍_2026-04-16T14-12-23+08-00.txt").write_text("", encoding="utf-8")

    result = collect_delivery_files(str(tmp_path))

    assert [Path(path).name for path in result] == ["a.pdf", "b.txt", "c.docx"]


def test_copy_directory_filtered_excludes_generated_text_files(tmp_path: Path):
    source_dir = tmp_path / "source"
    target_dir = tmp_path / "target"
    source_dir.mkdir()

    (source_dir / "正文.pdf").write_text("pdf", encoding="utf-8")
    (source_dir / "商品介绍_2026-04-16T14-12-23+08-00.txt").write_text("intro", encoding="utf-8")
    (source_dir / "文件清单_2026-04-16T14-12-23+08-00.txt").write_text("list", encoding="utf-8")
    (source_dir / "商品图片").mkdir()
    (source_dir / "商品图片" / "01_封面_2026-04-16T14-12-23+08-00.png").write_text("img", encoding="utf-8")

    success, result = copy_directory_filtered(str(source_dir), str(target_dir))

    assert success is True
    assert Path(result) == target_dir
    assert (target_dir / "正文.pdf").exists()
    assert not any(path.name.startswith("商品介绍_") for path in target_dir.iterdir())
    assert not any(path.name.startswith("文件清单_") for path in target_dir.iterdir())
    assert not (target_dir / "商品图片").exists()


def test_is_generated_helper_file_matches_timestamped_names():
    assert is_generated_helper_file("商品介绍_2026-04-16T14-12-23+08-00.txt") is True
    assert is_generated_helper_file("商品介绍汇总_2026-04-16T14-12-23+08-00.txt") is True
    assert is_generated_helper_file("01_封面_2026-04-16T14-12-23+08-00.png") is True
    assert is_generated_helper_file("info_2026-04-16T14-12-23+08-00.txt") is True
    assert is_generated_helper_file("正文.pdf") is False


def test_clear_generated_artifacts_removes_timestamped_files_and_image_dir(tmp_path: Path):
    (tmp_path / "商品介绍_2026-04-16T14-12-23+08-00.txt").write_text("", encoding="utf-8")
    (tmp_path / "文件清单_2026-04-16T14-12-23+08-00.txt").write_text("", encoding="utf-8")
    (tmp_path / "正文.pdf").write_text("", encoding="utf-8")
    image_dir = tmp_path / "商品图片"
    image_dir.mkdir()
    (image_dir / PRODUCT_IMAGE_MARKER_FILENAME).write_text("Generated by BookFlow.\n", encoding="utf-8")
    (image_dir / "01_封面_2026-04-16T14-12-23+08-00.png").write_text("", encoding="utf-8")

    clear_generated_artifacts(str(tmp_path))

    assert not (tmp_path / "商品介绍_2026-04-16T14-12-23+08-00.txt").exists()
    assert not (tmp_path / "文件清单_2026-04-16T14-12-23+08-00.txt").exists()
    assert not image_dir.exists()
    assert (tmp_path / "正文.pdf").exists()


def test_clear_generated_artifacts_keeps_unmarked_image_dir(tmp_path: Path):
    image_dir = tmp_path / "商品图片"
    image_dir.mkdir()
    (image_dir / "manual-note.txt").write_text("keep", encoding="utf-8")

    clear_generated_artifacts(str(tmp_path))

    assert image_dir.exists()
    assert (image_dir / "manual-note.txt").exists()


def test_is_program_owned_image_dir_requires_marker_file(tmp_path: Path):
    image_dir = tmp_path / "商品图片"
    image_dir.mkdir()

    assert is_program_owned_image_dir(str(image_dir)) is False

    (image_dir / PRODUCT_IMAGE_MARKER_FILENAME).write_text("Generated by BookFlow.\n", encoding="utf-8")

    assert is_program_owned_image_dir(str(image_dir)) is True
